In [1]:
import numpy as np
a=np.array([1,2,3])
print("type: %s" %type(a))
print("shape: %s" %a.shape)
print(a[0],a[1],a[2])
a[0]=5
print(a)
b=np.array([[1,2,3],[4,5,6]])
print("\nShape of b %s",b.shape)
print(b[0,0],b[0,1],b[1,0])
a=np.zeros((2,2))
print("All zeros matrix: \n%s"%a)
b=np.ones((1,2))
print("All ones matrix: \n %s"%b)
d=np.eye(2)
print("\nIdentity matrix: \n%s"%d)
e=np.random.random((2,2))
print("\nRandom matrix: \n %s"%e)
print("vectorized sum example \n")
x=np.array([[1,2],[3,4]])
print("x: \n%s"%x)
print("sum:%s" %np.sum(x))
print("sum axis=0:%s"%np.sum(x,axis=0))
print("sum axis=0: %s"%np.sum(x,axis=1))
a=np.arange(10000)
b=np.arange(10000)
dp=np.dot(a,b)
print("dot product:%s\n"%dp)
op=np.outer(a,b)
print("\nOuter product:%s \n"%op)
ep=np.multiply(a,b)
print("\nElement wide product:%s \n"%ep)

type: <class 'numpy.ndarray'>
shape: 3
1 2 3
[5 2 3]

Shape of b %s (2, 3)
1 2 4
All zeros matrix: 
[[0. 0.]
 [0. 0.]]
All ones matrix: 
 [[1. 1.]]

Identity matrix: 
[[1. 0.]
 [0. 1.]]

Random matrix: 
 [[0.38106059 0.21483924]
 [0.98064876 0.02484344]]
vectorized sum example 

x: 
[[1 2]
 [3 4]]
sum:10
sum axis=0:[4 6]
sum axis=0: [3 7]
dot product:-1724114088


Outer product:[[       0        0        0 ...        0        0        0]
 [       0        1        2 ...     9997     9998     9999]
 [       0        2        4 ...    19994    19996    19998]
 ...
 [       0     9997    19994 ... 99940009 99950006 99960003]
 [       0     9998    19996 ... 99950006 99960004 99970002]
 [       0     9999    19998 ... 99960003 99970002 99980001]] 


Element wide product:[       0        1        4 ... 99940009 99960004 99980001] 

